**Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.**

1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy.
Полученные значения должны быть равны.

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [3]:
import numpy as np
import pandas as pd

In [4]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [6]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [8]:
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [10]:
np.cov(zp,ks, ddof = 0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Полученные разными способами значения ковариации равны

Коэффициент корреляции Пирсона:

In [13]:
std_zp = np.sqrt(((zp - zp.sum()/zp.size)**2).sum() / zp.size)
std_zp

59.115480206118605

In [14]:
std_ks = np.sqrt(((ks - ks.sum()/ks.size)**2).sum() / ks.size)
std_ks

174.55340157098058

In [16]:
r = cov / (std_zp * std_ks)
r

0.8874900920739158

In [17]:
cov / (np.std(ks) * np.std(zp))

0.8874900920739158

In [18]:
df = pd.DataFrame({'zp':zp, 'ks':ks})
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [20]:
df.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

In [27]:
df.corr().iloc[0,1]

0.8874900920739162

In [39]:
df.std(axis=0, ddof = 0)

zp     59.115480
ks    174.553402
dtype: float64

In [42]:
cov / (df.std(axis=0, ddof = 0)[0] * df.std(axis=0, ddof = 0)[1])

0.8874900920739158